# Generated by Django 6.0.1 on 2026-02-03 06:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='최대 5MB, 1000x1000 픽셀 권장', upload_to='food_images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='제목')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '음식 이미지',
                'verbose_name_plural': '음식 이미지 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='내용')),
                ('visibility', models.CharField(choices=[('public', '공개'), ('private', '비공개')], default='private', max_length=10, verbose_name='공개 설정')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='receipts/%Y/%m/%d/', verbose_name='영수증 이미지')),
                ('ocr_text', models.TextField(blank=True, verbose_name='추출된 텍스트')),
                ('is_processed', models.BooleanField(default=False, verbose_name='처리 완료')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '영수증',
                'verbose_name_plural': '영수증 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='레시피 제목')),
                ('content', models.TextField(max_length=300, validators=[django.core.validators.MaxLengthValidator(300)], verbose_name='레시피 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0, verbose_name='조회수')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '레시피',
                'verbose_name_plural': '레시피 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
