# Generated by Django 6.0.1 on 2026-02-05 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecook', '0002_recipe_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='나의 챌린지', max_length=100, verbose_name='챌린지 제목')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '챌린지 세트',
                'verbose_name_plural': '챌린지 세트 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='foodimage',
            name='challenge_set',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_image', to='homecook.challengeset'),
        ),
        migrations.AddField(
            model_name='journal',
            name='challenge_set',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='homecook.challengeset'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='challenge_set',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='homecook.challengeset'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='challenge_set',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='homecook.challengeset'),
        ),
    ]
