# Generated by Django 6.0.1 on 2026-02-10 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homecook', '0003_challengeset_foodimage_challenge_set_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['-created_at'], 'verbose_name': '기록장', 'verbose_name_plural': '기록장 목록'},
        ),
    ]
