# Generated by Django 6.0.1 on 2026-02-10 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homecook', '0004_alter_journal_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='ocr_text',
        ),
    ]
