# Generated by Django 6.0.1 on 2026-02-05 02:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', '입금'), ('withdrawal', '출금'), ('transfer', '이체')], max_length=20, verbose_name='거래 유형')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='금액')),
                ('category', models.CharField(choices=[('food', '식비'), ('transport', '교통비'), ('shopping', '쇼핑'), ('utility', '공과금'), ('entertainment', '여가/문화'), ('income', '수입'), ('other', '기타')], max_length=20, verbose_name='카테고리')),
                ('description', models.CharField(help_text='거래 내용을 입력하세요 (최대 200자)', max_length=200, verbose_name='내용')),
                ('balance_after', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='거래 후 잔액')),
                ('transaction_date', models.DateTimeField(verbose_name='거래 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('memo', models.TextField(blank=True, help_text='추가 메모 (선택사항, 최대 500자)', max_length=500, verbose_name='메모')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '거래내역',
                'verbose_name_plural': '거래내역 목록',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-transaction_date'], name='information_user_id_abdac0_idx'), models.Index(fields=['transaction_type'], name='information_transac_fbc15a_idx'), models.Index(fields=['category'], name='information_categor_17e763_idx')],
            },
        ),
    ]
