# Generated by Django 4.2.7 on 2026-02-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('food', '식비'), ('transport', '교통비'), ('shopping', '쇼핑'), ('utility', '공과금'), ('entertainment', '여가/문화'), ('income', '수입'), ('other', '기타'), ('health_point', '건강 포인트')], max_length=20, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', '입금'), ('withdrawal', '출금'), ('transfer', '이체'), ('seoulpay', '서울페이')], max_length=20, verbose_name='거래 유형'),
        ),
    ]
