# Generated by Django 4.2.7 on 2026-02-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('salary', '월급'), ('allowance', '용돈'), ('food', '식비'), ('transport', '교통비'), ('shopping', '쇼핑'), ('utility', '공과금'), ('entertainment', '여가/문화'), ('health_point', '건강 포인트'), ('other', '기타')], max_length=20, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', '입금'), ('withdrawal', '출금'), ('samsungpay', '삼성페이'), ('seoulpay', '서울페이')], max_length=20, verbose_name='거래 유형'),
        ),
    ]
