# Generated by Django 4.2.7 on 2026-02-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', '입금'), ('withdrawal', '출금'), ('seoulpay', '서울페이')], max_length=20, verbose_name='거래 유형'),
        ),
    ]
