# Generated by Django 6.0.1 on 2026-02-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, default='', help_text='거래 내용을 입력하세요 (선택사항, 최대 200자)', max_length=200, verbose_name='내용'),
        ),
    ]
