# Generated by Django 6.0.1 on 2026-02-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_alter_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('salary', '월급'), ('allowance', '용돈'), ('food', '식비'), ('transport', '교통비'), ('shopping', '쇼핑'), ('utility', '공과금'), ('entertainment', '여가/문화'), ('health_point', '건강 포인트'), ('rent', '월세'), ('interest', '이자'), ('maintenance', '관리비'), ('other', '기타')], max_length=20, verbose_name='카테고리'),
        ),
    ]
