# Generated by Django 6.0.1 on 2026-02-11 16:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_alter_transaction_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('kb', 'KB국민'), ('shinhan', '신한'), ('woori', '우리'), ('hana', '하나'), ('nh', 'NH농협'), ('ibk', 'IBK기업'), ('kakao', '카카오뱅크'), ('toss', '토스뱅크'), ('other', '기타')], max_length=20, verbose_name='은행명')),
                ('account_number', models.CharField(help_text='계좌번호를 입력하세요 (최대 30자)', max_length=30, verbose_name='계좌번호')),
                ('account_alias', models.CharField(blank=True, default='', help_text='구분하기 쉬운 별칭을 입력하세요 (선택사항)', max_length=50, verbose_name='계좌 별칭')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='잔액')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_info', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '계좌',
                'verbose_name_plural': '계좌 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='information.account', verbose_name='계좌'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', '-created_at'], name='information_user_id_59caf7_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['bank_name'], name='information_bank_na_5f09c4_idx'),
        ),
    ]
